### ISSUE TITLE
Add links

### ISSUE THREAD

**Issue by raderio** [aalhour/awesome-compilers#14]
Some links 
https://medium.freecodecamp.com/the-programming-language-pipeline-91d3f449c919
http://beautifulracket.com/
http://blog.ppelgren.se/2015-01-03/DIY-Make-Your-Own-Programming-language/
https://web.archive.org/web/20161025093116/http://nathansuniversity.com/
http://eloquentjavascript.net/11_language.html
http://lisperator.net/pltut/

**Comment by aalhour** [comment]
Hi! Thanks for sharing these links, some of them are actually in the list already.
