### ISSUE TITLE
Keystone & Capstone

### ISSUE THREAD

**Issue by arBmind** [aalhour/awesome-compilers#21]
Hi, since you asked for more tooling.

I guess these should be on your list as well.

### Keystone

https://github.com/keystone-engine/keystone

Basically a library that turns assembler from strings into byte sequences.

### Capstone

https://github.com/aquynh/capstone

Goes the other way and turns encoded assembly into assembler text & details.

**Comment by aalhour** [comment]
Thanks a lot for recommending such awesome resources, I have just added them to the list.
